#! /bin/sh
# Test performance of gzip and pigz

gzip="gzip"
gzippier="./gzip"
file1="random1.bin"
file2="random2.bin"
file3="random3.bin"

echo "Performance Comparison"

echo "Create a random 1GB file"
head -c 1073741824 </dev/urandom >${file1}
cp ${file1} ${file2}
cp ${file1} ${file3}

echo "old gzip compressing 1GB file"
time -f "\t%E real" ${gzip} ${file2}
${gzip} -d "${file2}.gz"
echo "new gzip compressing 1GB file"
time -f "\t%E real" ${gzippier} ${file3}
${gzippier} -d "${file3}.gz"

diff ${file2} ${file3}
# cleanup
rm ${file1} ${file2} ${file3}
