#! /bin/sh
# Test performance of gzip

. "${srcdir=.}/init.sh"; path_prepend_ ..

gzip="./gzip"
gzippier="../gzip"
filename="1GB.bin"
fail=0

Exit () { set +e; (exit $1); exit $1; }

test -x ${gzip} || fail=1
test -x ${gzippier} || fail=1

head -c 1073741824 </dev/urandom >${filename} || fail=1

# echo $filename
echo "Performance Comparison"
time ${gzip} -k ${filename} || fail=1
rm "${filename}.gz" || fail=1
echo ""
time ${gzippier} -k ${filename} || fail=1
rm "${filename}.gz" || fail=1
# cleanup
rm ${filename} || fail=1

if fail

Exit ${fail}
