#! /bin/sh
# Test signal handling for the gzip

pid=''
fail=0
filename="signal-segv"
gzip="./pigz"

test -x ${gzip} && exit 1

mkdir gt-signal
cd gt-signal

head -c 2000000 </dev/urandom >${filename}

set -x
for sig in \
    INT \
    HUP \
    PIPE \
    TERM \
    XCPU \
    XFSZ
do
  cp ${filename} "${filename}-${sig}" || fail=1
  ${gzip} "${filename}-${sig}" &
  pid=$!
  kill -${sig} ${pid} || fail=1
  test -f "${filename}-${sig}" || fail=1
  test -f "${filename}-${sig}.gz" && fail=1
  diff ${filename} "${filename}-${sig}" || fail=1
done

cd ..
chmod -R u+rwx gt-signal
rm -rf gt-signal

exit ${fail}
